// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package api

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnknownError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserServiceErrorReason_UNKNOWN_ERROR.String() && e.Code == 500
}

func ErrorUnknownError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, UserServiceErrorReason_UNKNOWN_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsCompanyNotExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserServiceErrorReason_COMPANY_NOT_EXIST.String() && e.Code == 404
}

func ErrorCompanyNotExist(format string, args ...interface{}) *errors.Error {
	return errors.New(404, UserServiceErrorReason_COMPANY_NOT_EXIST.String(), fmt.Sprintf(format, args...))
}
