// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"uims/app/orgms/api/internal/conf"
	"uims/app/orgms/api/internal/server"
	"uims/app/orgms/api/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	companyService := service.NewCompanyService()
	departmentService := service.NewDepartmentService()
	userService := service.NewUserService()
	httpServer := server.NewHTTPServer(confServer, companyService, departmentService, userService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, httpServer, registrar)
	return app, func() {
	}, nil
}
