trace:
  endpoint: http://152.136.131.96:14268/api/traces
server:
  grpc:
    addr: 127.0.0.1:9000
#    timeout: 1s
data:
  database:
    driver: mysql
    source: pears:cy7m0yp@,FperzI45@tcp(152.136.131.96:3306)/zxn_test?parseTime=true
  redis:
    addr: 152.136.131.96:6380
    read_timeout: 3s
    write_timeout: 3s
  kafka:
    addrs:
      - 152.136.131.96:9092
auth:
  key: some-secret-key